site_name: GSD Academy — Governança e Segurança de Dados
site_description: Plataforma de e-learning para a UC de Governança e Segurança de Dados
site_url: https://guilhasn.github.io/GSD-ACADEMY/
repo_url: https://github.com/guilhasn/GSD-ACADEMY
repo_name: GSD-ACADEMY
copyright: "© {year} Nuno Salvador"

theme:
  name: material
  language: pt
  features:
    - navigation.instant
    - toc.follow
  palette:
    - scheme: default
  icon:
    repo: fontawesome/brands/github
  extra_css:
    - 'assets/stylesheets/fullwidth.css'
  
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Início: index.md
  - ETAPA 1 — Business Case:
      - Introdução: ETAPA 1 - Business Case/etapa-01-business-case.md
      - Exemplo 1: ETAPA 1 - Business Case/exemplo1.md
      - Exemplo 2: ETAPA 1 - Business Case/exemplo2.md
      - Exemplo 3: ETAPA 1 - Business Case/exemplo3.md
      - Exemplo 4: ETAPA 1 - Business Case/exemplo4.md
      - Atividade Interativa: ETAPA 1 - Business Case/atividade-business-case.html
  - ETAPA 2 — Engagement:
      - Introdução: ETAPA 2 - Engagement/etapa-02-engagement.md
      - Simulador de Cenários: ETAPA 2 - Engagement/simulador-cenarios-engagement.html
  - ETAPA 3 — Estratégia:
      - Introdução: ETAPA 3 - Estratégia/etapa-03-estrategia.md
  - Recursos: recursos.md

