site_name: GSD Academy — Governança e Segurança de Dados
site_description: Plataforma de e-learning para a UC de Governança e Segurança de Dados
site_url: https://guilhasn.github.io/GSD-ACADEMY/
repo_url: https://github.com/guilhasn/GSD-ACADEMY
repo_name: GSD-ACADEMY
copyright: "© {year} Nuno Salvador"

theme:
  name: material
  language: pt
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - toc.follow
  palette:
    - scheme: default
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Início: index.md
  - Módulos:
      - Fundamentos: fundamentos.md
      - Business Case: business_case.md
      - Engagement & Deployment: engagement.md
  - Quizzes: quizzes.md
  - Recursos: recursos.md
  - Privacidade: privacidade.md
