site_name: GSD Academy — Governança e Segurança de Dados
site_description: Plataforma de e-learning para a UC de Governança e Segurança de Dados
site_url: https://guilhasn.github.io/GSD-ACADEMY/
repo_url: https://github.com/guilhasn/GSD-ACADEMY
repo_name: GSD-ACADEMY
copyright: "© {year} Nuno Salvador"

theme:
  name: material
  language: pt
  features:
    - navigation.instant
    - toc.follow
  palette:
    - scheme: default
  icon:
    repo: fontawesome/brands/github
  extra_css:
    - 'assets/stylesheets/fullwidth.css'
  
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Início: index.md
  - ETAPA 1 — Business Case:
      - Introdução: etapa-01-business-case.md
      - Atividade 1: ETAPA 1 - Business Case/atividade1.md
      - Atividade 2: ETAPA 1 - Business Case/atividade2.md
  - Quizzes: quizzes.md
  - Recursos: recursos.md
  - Privacidade: privacidade.md
